### ISSUE TITLE
Update Repository with new structure

### ISSUE THREAD

**Issue by KamiQuasi** [redhat-developer/developers.redhat.com#3006]
- [ ] Create submodule to rhd-frontend
- [ ] remove rhd-frontend from rhdp theme
- [ ] add top-level folder for rhd-frontend submodule (frontend)
- [ ] add Drupal Sass watcher
- [ ] add Drupal-specific CSS and JS (if necessary)

**Comment by robpblake** [comment]
We have this working temporarily in #3015 but with the following changes and omissions:

* `rhd-frontend` cannot live in the root of the repo because it's outside of the Docker build context. Currently it has been moved to a sub-module of the `rhdp2` theme.
* There are no watchers for rebuilding of the `dist` assets
* We're still trying to work out what CSS + JS is required from the current theme.

The above work is also temporary until we get the CDN build process working for the front-end assets. That is dependent upon:

* `rhd-frontend` building out dist assets in a way that we can consume and push to a CDN
* Working out what specific parts of the FontAwesome library is actually required (currently `rhd-frontend` is downloading ~150MB of JS for that, which is bloat I don't want to add to our Container image sizes)
* Getting the build process in place for `rhd-frontend` to publish the assets onto our CDN space.

**Comment by jordanpagewhite** [comment]
We will not be addressing these issues in this ticket. 

-  Create submodule to rhd-frontend (done in rhdp2 theme in #3015)
-   remove rhd-frontend from rhdp theme (we cannot do this, although we will be uninstalling the rhdp theme in #3015 )
-   add top-level folder for rhd-frontend submodule (frontend) (this will live in the rhdp2 theme in #3015 )
-   add Drupal Sass watcher (the SASS watcher will live in the FE project)
-   add Drupal-specific CSS and JS (if necessary) (this can be tackled in individual issues as necessary)

SEE #3015 for any further inquiries into this ticket
