### ISSUE TITLE
User Name/Last Name not displayed on mobile

### ISSUE THREAD

**Issue by adelasofia** [redhat-developer/developers.redhat.com#3253]
When logged in, the 'Log In' link on the mobile navigation should change to the User's name and last name. Currently, clicking it does direct you to the user's profile settings but the text stays 'Log In'.

**Comment by rogeralloymagnetic** [comment]
@adelasofia @joeschram Can you confirm this is still an issue? When I did a test login on developers.redhat.com I saw the opposite of what you describe. My name displayed correctly, but the link was `#` and didn't go to any sort of profile.

I don't think any of this logic is done in Drupal since the Drupal user model doesn't have a first and last name and there's no logic currently set to check for a logged in user. So, at this point I'm assuming it's some sort of legacy JS code somewhere and I'd like to verify we're all seeing the same behavior before going down the legacy rabbit-hole.

All that being said, I did find two front-end issues when testing this and would like to confirm if you are seeing them too before adding FE tickets for them.

### Logged in with correct name
![Screen Shot 2019-10-23 at 7 39 45 AM](https://user-images.githubusercontent.com/41014351/67399183-0e316480-f569-11e9-9572-30a945e39e14.png)

### Name link hover color wrong
![Screen Shot 2019-10-23 at 7 41 09 AM](https://user-images.githubusercontent.com/41014351/67399193-12f61880-f569-11e9-828e-a59686b8f930.png)

### Account Info hover looks like it's `display:inline`
![Screen Shot 2019-10-23 at 7 41 03 AM](https://user-images.githubusercontent.com/41014351/67399209-17223600-f569-11e9-8955-f05346635551.png)

**Comment by adelasofia** [comment]
@rogeralloymagnetic The issue with the name not appearing is only on the mobile navigation tray. See this screenshot:
![image](https://user-images.githubusercontent.com/8727648/67406344-2f974e00-f573-11e9-88cf-a13e74bf68e1.png)

As for the other issues, they have been fixed on https://github.com/redhat-developer/rhd-frontend/pull/391

**Comment by rogeralloymagnetic** [comment]
The text replacement functionality is working in the latest WIP PR. Waiting for FE/Drupal integration changes before restyling the nav.
