### ISSUE TITLE
CTA buttons on mobile viewport are not centered

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3254]
- Go to /home
- Inspect page, set device to phone 375x667
- Scroll down to More Articles CTA button, or Learn more CTA button
- See screenshots
<img width="404" alt="Screen Shot 2019-10-16 at 1 56 44 PM" src="https://user-images.githubusercontent.com/5090034/66945483-1d6e5a80-f01d-11e9-9560-8027f91ce9e9.png">

<img width="437" alt="Screen Shot 2019-10-16 at 2 00 39 PM" src="https://user-images.githubusercontent.com/5090034/66945675-70e0a880-f01d-11e9-855c-be641ff85e14.png">

**Comment by joeschram** [comment]
Another example to check after this fix goes in; the [RHEL8 Cheatsheet](https://developers.redhat.com/cheat-sheets/red-hat-enterprise-linux-8/)

Look at it in a mobile media viewport:

<img width="445" alt="Screen Shot 2019-10-16 at 8 56 17 PM" src="https://user-images.githubusercontent.com/5090034/66969456-94c0e000-f057-11e9-9c4d-f5e77bbef18b.png">

<img width="443" alt="Screen Shot 2019-10-16 at 8 56 23 PM" src="https://user-images.githubusercontent.com/5090034/66969462-97bbd080-f057-11e9-8cbc-7115d38545d1.png">

**Comment by rogeralloymagnetic** [comment]
@joeschram The dynamic_content_list CTA button issue is fixed in the PR below. The other pictured issue here is WYSIWYG content in a rich_text assembly, so that's a content issue. Same with the RHEL 8 content.

You should be able to put those buttons inside a div with a `pf-l-flex` class on them to fix those buttons in content.

PR: https://github.com/redhat-developer/developers.redhat.com/pull/3301
