### ISSUE TITLE
Decide which JIRA instance we use

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3380]
Estimate: 0

**Description**

We need to decide which JIRA instance we can use so we can resume running structured sprints and epics.

- JBoss JIRA
- CEE JIRA

**Comment by jordanpagewhite** [comment]
@eriknewby @joeschram Do we have a sense of what the action item(s) are on this issue and/or what question(s) remain unanswered?

**Comment by joeschram** [comment]
Hi guys…I know @jordanpagewhite wants this wrapped up soon, so here's my attempt to outline the choices.

1. Go with PnT JIRA, Dawn is already a super admin there, we can get set up quickly. Next steps would be to look at migration scripts to bring our old JIRAs over and the current Github state over. The drawbacks/unknowns here are:

- Behind VPN will require all our stakeholders (and the DX team) to get on VPN to file tickets
- No mobile app access
- Might have to migrate again? (not sure)
- What are the plans to move to a JIRA v8.x update? (unknown)

2. Go with JBoss JIRA, we'd ask Mark Newton to give Dawn super admin access, set her loose in there. Next steps would be: migrating existing JIRA issues (should be easier since it is the same instance), moving Github issues in. The drawbacks/unknowns are:

- Will MWES org give Dawn super admin access?
- Might have to migrate again? (not sure)
- What are the plans to move to a JIRA v8.x update? (unknown)

That's the situation as I know it.

@eriknewby what did Shea have to say about any of the above? And do we need to get Mark Newton into the mix?

**Comment by eriknewby** [comment]
Yea sorry, on PTO this week. Poor timing given we need to make this decision. Yes, Dawn and I both met with the program lead for Omega Prime, Red Hat's issue tracking consolidation project. Shea also suggests that we go ahead and move forward with the PnT instance. This will allow us to be effective and more productive sooner. The truth is, even github will eventually be consolidated to Jira in the future. And with the admin support on the PnT side, we can smoke out our ideal workflow. Shea isn't concerned about the migration from PnT to jboss instance in a quarter+. We will stay in communication on that front with him.
Dawn will eventually have admin access on the jboss side as well.

**Comment by joeschram** [comment]
Sounds like we're going to PnT JIRA then. Ok @jordanpagewhite let's fire it up.

**Comment by jordanpagewhite** [comment]
Great, sounds good. This seems resolve then. We just need to make the time to move over some issues and get organized. This resolves all of the action items in this issue, so I will close it. Thank you both.
