### ISSUE TITLE
Jump-to nav has no margins

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3387]
Estimate: 1

**Description**
The jump-to nav has no margins on larger viewports so it's getting flushed left.

**To Reproduce**
1. Go to any page with jump nav... developers.redhat.com/topics/istio/service-mesh
2. See the no padding

**Expected behavior**
The component should have the same margins as the rest of the content on the page and should match the expanding margins once at the larger breakpoint (as the rest of the site has). Margins on tablet and mobile **are correct**.

**Screenshots/GIFs**
<img width="1680" alt="Screen Shot 2019-11-19 at 9 56 39 AM" src="https://user-images.githubusercontent.com/30870144/69157703-546bdc00-0ab3-11ea-8b1b-42fa06663fe5.png">

**Additional context**

**Comment by staceymosier** [comment]
It looks like the path to the page has changed, https://developers.redhat.com/topics/service-mesh/

**Comment by staceymosier** [comment]
The other components (divs with .component class) have a child of .pf-l-flex or .pf-l-grid.  
Other assembly twig files are using the pf classes,   just commenting here since I spent some time looking at it.


<img width="1494" alt="assembly-page_navigation" src="https://user-images.githubusercontent.com/19995927/70066912-75582500-15bb-11ea-9122-c9056afc2ebf.png">
