### ISSUE TITLE
Update Readme for Fedora Environment

### ISSUE THREAD

**Issue by mindreeper2420** [redhat-developer/developers.redhat.com#3429]
Currently, the Readme.md for for the rhd-frontend folder does not document how to figure a Fedora environment to run the frontend code. The current instructions are for MacOS.

**Comment by KamiQuasi** [comment]
@mindreeper2420 not sure this is entirely true. There are notes for Mac users in there, but those were actually written after the fact because I didn't have a Mac. There are some assumptions probably that could be documented though (specifically the commands to add Node and Go).  Generally though the commands should be relatively OS agnostic.
