### ISSUE TITLE
Link goes to "Internal Server Error"

### ISSUE THREAD

**Issue by PortStone** [redhat-developer/developers.redhat.com#3603]
**Description**
If I am on https://developers.redhat.com/products/codeready-containers/overview?ref=learn-developing-with-odo clicking the red button that says "Install OpenShift on your laptop" will redirect me to https://developers.redhat.com/content-gateway/link/3868678 with the following contents: 
```
Internal Server Error - Read
The server encountered an internal error or misconfiguration and was unable to complete your request.
Reference #3.854a0760.1633278393.b8edd340
```

**To Reproduce**
1. Go to https://developers.redhat.com/products/codeready-containers/overview?ref=learn-developing-with-odo
2. Click on  the red button that says "Install OpenShift on your laptop"
3. See error/issue

**Expected behavior**
I should see a actual site to download CodeReady Containers.

**Comment by audioroger** [comment]
Hi @PortStone thanks for bring up this issue! I'm the dev lead for developers.redhat.com and do want to note that this project has moved off of Github and into an internal repository. As such, this is no longer reviewing open issues.

However, I did follow your reproduction steps (thanks for those) and was not able to replicate it as of this morning. I'm assuming it was a temporary service outage leading to this error and it has since been resolved.

If this is still an issue or you have any other concerns please open up a ticket using the "Report a website issue" link in the "Communicate" section of our footer here: https://developers.redhat.com/ That will open a bug report and notify the proper channels.
